# Generated by Django 5.2 on 2025-04-23 17:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_rename_added_at_wishlist_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='entry',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='Ma wishlist', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='entries.wishlist'),
        ),
    ]
