# Generated by Django 5.2 on 2025-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_remove_wishlist_entry_wishlist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='style',
            field=models.CharField(choices=[('php', 'PHP'), ('js', 'JavaScript'), ('frameworks', 'Frameworks'), ('cms', 'CMS'), ('git', 'GIT')], default='autre', max_length=50),
        ),
    ]
