# Generated by Django 5.2 on 2025-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_entry_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='style',
            field=models.CharField(choices=[('PHP', 'PHP'), ('JavaScript', 'JavaScript'), ('Frameworks', 'Frameworks'), ('CMS', 'CMS'), ('GIT', 'GIT')], default='autre', max_length=50),
        ),
    ]
