# Generated by Django 5.2 on 2025-04-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_alter_entry_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='style',
            new_name='subject',
        ),
    ]
